apiVersion: v1
description: Connect OpenFaaS functions to Kafka topics
name: kafka-connector
version: 0.6.5
sources:
- https://github.com/openfaas/faas-netes
home: https://www.openfaas.com
icon: https://raw.githubusercontent.com/openfaas/media/master/OpenFaaS_logo_stacked_opaque.png
keywords:
- functions
- service
- kafka
- pro
maintainers:
- name: alexellis
  email: alex@openfaas.com
